# Site wide configuration

title: Christian HB9HOX
#description: About amateur radio
logo: images/site-logo.png
url: https://hb9hox.radio

# Theming
theme: jekyll-theme-so-simple

# Site owner
author:
  name: Christian HB9HOX
  picture: images/christian.jpg
  links:
    - &email
      title: Email
      url: mailto:qsl@hb9hox.radio
      icon: fas fa-envelope
    - &qrz
      title: QRZ
      url: https://www.qrz.com/db/HB9HOX
      icon: fas fa-globe
    - &github
      title: GitHub
      url: http://github.com/corvus-ch
      icon: fab fa-github

# Front matter defaults
defaults:
  - scope:
      path: ""
    values:
      lang: en
  - scope:
      path: "_*/en"
    values:
      permalink: /en/:categories/:year-:month-:day-:title:output_ext
  - scope:
      path: "_*/de"
    values:
      lang: de
      permalink: /de/:categories/:year-:month-:day-:title:output_ext

asciidoctor:
  template_dir: _templates
  attributes:
    icon-map:
      note: fas fa-info-circle
      tip: fas fa-lightbulb
      warning: fas fa-exclamation-triangle
      caution: fas fa-fire
      important: fas fa-exclamation-circle


# Footer Links
footer_links:
  - *email
  - *qrz
  - *github
  - title: Feed
    url: feed.xml
    icon: fas fa-rss

# Build settings
plugins:
  - jekyll-feed

exclude:
  - Dockerfile
  - Gemfile
  - Gemfile.lok
  - Makefile
