name: GitHub Pages

on:
  push:
    branches:
      - trunk
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Setup Aciidoctor
        run: gem install asciidoctor tilt

      - name: Build
        run: |
          export PATH=$GITHUB_WORKSPACE/scripts:$PATH
          hugo --verbose --minify --printI18nWarnings --baseURL hb9hox.radio

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/trunk' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
